### PR TITLE
bug: delete existing .git directory if push-to-git and overwrite are set

### LINKED ISSUE #212: Bootstrap command fails to use existing remote origin in GitOps resources
**Describe the bug**
bootstrap command fails to use use existing remote origin in GitOps resources

**To Reproduce**
```
1. $ kam bootstrap --service-repo-url https://github.com/amitkrout/taxi --gitops-repo-url https://github.com/amitkrout/gitops.git --git-host-access-token ****** --push-to-git=true --output bootstrapresources
Checking dependencies
 [...]
 Next Steps:
 Please refer to https://github.com/redhat-developer/kam/tree/master/docs to get started.

2. Delete the gitops repo https://github.com/amitkrout/gitops.git

3. $ kam bootstrap --service-repo-url https://github.com/amitkrout/taxi --gitops-repo-url https://github.com/amitkrout/gitops.git --git-host-access-token ****** --push-to-git=true --output bootstrapresources --overwrite 
  
[...]
 ✓  Created dev, stage and CICD environments
 ✗  failed to create the gitops repository: "https://github.com/amitkrout/gitops.git": failed to push bootstrapped resources: failed add remote 'origin' "git@github.com:amitkrout/gitops.git" to repository in "bootstrapresources" "fatal: remote origin already exists.\n": exit status 128
```
**Expected behavior**

kam bootstrap should reuse the remote origin or may be overwritten 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by ishitasequeira**
Resolves issue https://github.com/redhat-developer/kam/issues/212

**What type of PR is this?**
/kind bug

**Why we need it**:

The bootstrap command  
```
kam bootstrap --service-repo-url https://github.com/ishitasequeira/taxi --gitops-repo-url https://github.com/ishitasequeira/gitops.git --image-repo quay.io/isequeir/taxi --dockercfgjson isequeir-robot-auth.json --git-host-access-token ******* --output resources --overwrite --push-to-git=true
``` 
when applied to the existing output directory, the folder gets updated but the remote origin does not get updated according to the new repo and the bootstrap command fails with below error.

**What does this PR do**:
In this PR, we fix the above issue. While executing the bootstrap command, we check if the overwrite flag is set  or not set, `--push-to-git=true` and if the `.git` directory exists in the OutputPath. for `push-to-git=true`, if the overwrite flag is not set and the `.git` directory is present, we return an error and If the overwrite flag is set, we remove the existing `.git` directory before performing `git init` in the OutputPath.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #212 

**How to test changes / Special notes to the reviewer**:

**Pre-Steps:**
1. Execute the initial bootstrap command for the first time
```
kam bootstrap --service-repo-url https://github.com/ishitasequeira/taxi.git --gitops-repo-url https://github.com/<username>/gitops.git  --image-repo quay.io/isequeir/image-repo --dockercfgjson ~/Downloads/<username>-robot-auth.json --git-host-access-token ****  --output ~/go/src/github.com/test/gitops --push-to-git=true
```

2. The above command will succeed successfully as it is executed for the first time.
3. Delete the `pipelines.yaml` and the secrets directory from the OutputPath. 

**Scenario 1:** The .git directory exists in the OutputPath and the overwrite flag is not set with `push-to-git=true`:

4. Delete the repository from GitHub created in above command
5. Execute the same command as above: (without the overwrite flag)
```
kam bootstrap --service-repo-url https://github.com/ishitasequeira/taxi.git --gitops-repo-url https://github.com/<username>/gitops.git  --image-repo quay.io/isequeir/image-repo --dockercfgjson ~/Downloads/<username>-robot-auth.json --git-host-access-token ****  --output ~/go/src/github.com/test/gitops --push-to-git=true
```

The above command will give below error and the bootstrap command will fail as the .git directory is present in the OutputPath. Also, as the above command failed, it does not create the repository.

```
 ✗  .git directory in output path already exists. If you want to replace your existing files, please rerun with --overwrite
```

**Scenario 2:** The .git directory exists in the OutputPath and the overwrite flag is set and `push-to-git=true`:

 6. Execute the below command 
```
kam bootstrap --service-repo-url https://github.com/ishitasequeira/taxi.git --gitops-repo-url https://github.com/<username>/gitops.git  --image-repo quay.io/isequeir/image-repo --dockercfgjson ~/Downloads/<username>-robot-auth.json --git-host-access-token ****  --output ~/go/src/github.com/test/gitops  --overwrite --push-to-git=true
```
The above command should now complete successfully .

 7. To confirm the remote was correctly set, execute ` git remote -v` in the OutputPath
```
$ git remote -v
origin  git@github.com:ishitasequeira/gitops.git (fetch)
origin  git@github.com:ishitasequeira/gitops.git (push)
```

**Scenario 3:** The .git directory exists in the OutputPath and `push-to-git=false`

8. Execute the below command
```
./kam bootstrap --service-repo-url https://github.com/ishitasequeira/taxi.git --gitops-repo-url https://github.com/ishitasequeira/gitops.git  --image-repo quay.io/isequeir/image-repo --dockercfgjson ~/Downloads/isequeir-robot-auth.json --git-host-access-token 5d51786484454160e5418b4d35e4ae257d6487f3  --output ~/go/src/github.com/openshift/redhat-developer/test
```
The above command succeeds even if the OutputPath contains `.git` directory as `push-to-git=false`.

***Interactive mode***

The interactive command fails with below error message if we decide to push to git and the OutputPath contains the `.git` directory.
```
$ ./kam bootstrap
  
Checking dependencies

 ✓  Checking if Sealed Secrets is installed with the default configuration [114ms]
 ✓  Checking if ArgoCD is installed with the default configuration [227ms]
 ✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [263ms]
  
Starting interactive prompt

? Do you want to accept all default values and be prompted only for the minimum required options? no
? You are able to seal secrets. Select Sealed to continue or Unsealed to generate unsealed secrets, which is not recommended. Sealed
? Provide the URL for your GitOps repository https://github.com/ishitasequeira/gitops.git
? Select type of image registry Openshift Internal registry
? Image registry of the form <project>/<app> which is used to push newly built images. test/app
? Provide a secret (minimum 16 characters) that we can use to authenticate incoming hooks from your Git hosting service for repository: https://github.com/ishitasequeira/gitops.git. (if not provided, it will be auto-generated) [? for help] 
? Provide the URL for your Service repository e.g. https://github.com/organisation/service.git https://github.com/ishitasequeira/taxi.git
? Provide a secret (minimum 16 characters) that we can use to authenticate incoming hooks from your Git hosting service for repository: https://github.com/ishitasequeira/taxi.git. (if not provided, it will be auto-generated) [? for help] 
? Please provide a token used to authenticate requests to "https://github.com/ishitasequeira/taxi.git" [? for help] ****************************************
? Do you wish to securely store the git-host-access-token in the keyring on your local machine? no
? Do you want to create and push the resources to your gitops repository? yes
? Add a prefix to the environment names(dev, stage, cicd etc.) to distinguish and identify individual environments? 
? Provide a path to write GitOps resources? /Users/ishitasequeira/go/src/github.com/openshift/redhat-developer/test
 ✗  the .git folder in output path /Users/ishitasequeira/go/src/github.com/openshift/redhat-developer/test already exists. Delete or rename the .git folder and try again
```

### CODE REVIEW

File: pkg/pipelines/utils_test.go [hunk 1]
```diff
@@ -113,6 +118,64 @@ func TestPushRepository(t *testing.T) {
...
+		[]byte("Initialized empty Git repository in /tmp/.git/"),
+		[]byte(""),
+	}
+	e := newMockExecutor(outputs...)
+	testErr := errors.New("test error")
+	e.errors.push(testErr)
+	e.errors.push(nil)
+	e.errors.push(nil)
+	e.errors.push(nil)
+	e.errors.push(nil)
```
Comment (amitkrout) [inline pkg/pipelines/utils_test.go:136]: Duplicate lines, no ?

**Comment by amitkrout** [comment]
Verified locally. Looks good. 
/approve

@chetan-rns Can you please review it implementation point of view

File: pkg/pipelines/utils_test.go (hunk 1 above)
Comment (ishitasequeira) [reply pkg/pipelines/utils_test.go:136]: Need to push the error messages as nil to the stack so that it gives required error only for the targeted check..

File: pkg/pipelines/utils.go [hunk 2]
```diff
@@ -86,8 +86,14 @@ func pushRepository(o *BootstrapOptions, remote string, e executor) error {
 	if out, err := e.execute(o.OutputPath, "git", "branch", "-m", "main"); err != nil {
 		return fmt.Errorf("failed to switch to branch 'main' in repository in %q %q: %s", o.OutputPath, string(out), err)
 	}
-	if out, err := e.execute(o.OutputPath, "git", "remote", "add", "origin", remote); err != nil {
-		return fmt.Errorf("failed add remote 'origin' %q to repository in %q %q: %s", remote, o.OutputPath, string(out), err)
+	if _, err := e.execute(o.OutputPath, "git", "remote", "show", "origin"); err != nil {
+		if out, err := e.execute(o.OutputPath, "git", "remote", "add", "origin", remote); err != nil {
```
Comment (shubhamagarwal19) [inline pkg/pipelines/utils.go:90]: we can probably just have an error check here? 
if `err contains "remote origin already exists"` we can call `git remote set-url`, if the error is something else just return the error.
What do you think?

**Comment by chetan-rns** [comment]
@amitkrout I think this PR is solving #212 rather than #207. WDYT?

**Comment by shubhamagarwal19** [comment]
> @amitkrout I think this PR is solving #212 rather than #207. WDYT?

@chetan-rns, yes !! it definitely fixes #212, I am not really sure what exactly is the error with issue #207!

**Comment by wtam2018** [comment]
Please update this PR to correctly point to which issue it is fixing.   Please update the description as well.   BTW, I don't think #212 is a bug.

**Comment by ishitasequeira** [comment]
> Please update this PR to correctly point to which issue it is fixing. Please update the description as well. BTW, I don't think #212 is a bug.
@wtam2018  I have updated the PR to https://github.com/redhat-developer/kam/issues/212. https://github.com/redhat-developer/kam/issues/212 seems to be a bug since the overwrite flag replaces the existing bootstrap directory to the new one. When the output directory gets updated with the new one, the remote alias origin does not get updated. As we are using remote add, there is a remote url origin already present and it needs to be updated with the new url.

**Review by shubhamagarwal19 — APPROVED** [review]
Thanks @ishitasequeira. 
/LGTM

**Comment by wtam2018** [comment]
Please update "how to test"

**Comment by ishitasequeira** [comment]
> Please update "how to test"

I have updated

**Comment by wtam2018** [comment]
We don't know what else is in the .git.  It is better off to check if .git exist.  If it does exist, we should fail the command with the appropriate error.   If there is an overwrite flag, we can remove the .git folder.

**Comment by wtam2018** [comment]
When push-to-git was implemented, one of the assumptions was that the git repo had not been initialized.   Now, you are running a sequence of git commands with an initialized repo in an unknown state.

**Comment by shubhamagarwal19** [comment]
> When push-to-git was implemented, one of the assumptions was that the git repo had not been initialized. Now, you are running a sequence of git commands with an initialized repo in an unknown state.

@wtam2018, this would only happen when the user explicitly provides `--overwrite` flag while bootsrapping. 
Right now, when the overwrite flag is provided, it updates the local output directory but doesn't push it to the git which is not consistent. 
So IMO, if the user is OK to overwrite the local output directory, it should be OK to update the git repo as well.

File: pkg/pipelines/utils.go [hunk 3]
```diff
@@ -87,7 +87,13 @@ func pushRepository(o *BootstrapOptions, remote string, e executor) error {
 		return fmt.Errorf("failed to switch to branch 'main' in repository in %q %q: %s", o.OutputPath, string(out), err)
 	}
 	if out, err := e.execute(o.OutputPath, "git", "remote", "add", "origin", remote); err != nil {
-		return fmt.Errorf("failed add remote 'origin' %q to repository in %q %q: %s", remote, o.OutputPath, string(out), err)
+		if strings.Contains(string(out), "remote origin already exists") {
```
Comment (shubhamagarwal19) [inline pkg/pipelines/utils.go:90]: can you check for `overwrite` flag here as well?

**Comment by shubhamagarwal19** [comment]
> We don't know what else is in the .git. It is better off to check if .git exist. If it does exist, we should fail the command with the appropriate error. If there is an overwrite flag, we can remove the .git folder.

aaahhh i missed this comment. 
Yes! it actually does make more sense to check for `.git` directory and `overwirte` flag. If `overwrite=true` delete the `.git` folder and reinitialize it.

**Comment by ishitasequeira** [comment]
> When push-to-git was implemented, one of the assumptions was that the git repo had not been initialized. Now, you are running a sequence of git commands with an initialized repo in an unknown state.

@wtam2018 I have addressed the comments

**Comment by wtam2018** [comment]
@ishitasequeira  I don't think "How to test changes " is correct.  You need to delete the gitops remote after step 4.   "Both commands should execute successfully" does not seem to make sense,

File: pkg/pipelines/utils.go [hunk 4]
```diff
@@ -74,6 +77,12 @@ func BootstrapRepository(o *BootstrapOptions, f clientFactory, e executor) error
 }
 
 func pushRepository(o *BootstrapOptions, remote string, e executor) error {
+	exists, _ := ioutils.IsExisting(ioutils.NewFilesystem(), filepath.Join(o.OutputPath, ".git"))
```
Comment (wtam2018) [inline pkg/pipelines/utils.go:80]: 1.  We should only do so if --overwrite is true.
2.  If --overwrite is false and --push-to-git is true and .git exists, we should return a error message.   If possible, an error is return before we start performing "push to git" (i.e. we should not true to create a new git repo if --overwrite is false and .git exists)

Comment (shubhamagarwal19) [reply pkg/pipelines/utils.go:80]: @ishitasequeira, are you assuming that if `--overwrite=false` and `output` directory exists then it would error out even before it tries to update the contents of the `output` directory? 
If that is true, i think its OK to not have the `--overwrite` check here!

Comment (ishitasequeira) [reply pkg/pipelines/utils.go]: @wtam2018 As discussed today, I have addressed the comments. I have updated the PR description as well.
@shubhamagarwal19 I have updated the workflow to check for overwrite flag and `.git` directory and return an error before creating the github repository if the directory exists and overwrite flag is false.

File: pkg/pipelines/bootstrap_test.go [hunk 5]
```diff
@@ -374,6 +376,37 @@ func TestOverwriteFlag(t *testing.T) {
...
+		Prefix:               "tst-",
+		GitOpsRepoURL:        testGitOpsRepo,
+		ImageRepo:            "image/repo",
+		GitOpsWebhookSecret:  "123",
+		GitHostAccessToken:   "test-token",
+		ServiceRepoURL:       testSvcRepo,
+		ServiceWebhookSecret: "456",
+		OutputPath:           "/tmp",
+	}
+	err := os.MkdirAll(filepath.Join(params.OutputPath, ".git"), 0755)
```
Comment (wtam2018) [inline pkg/pipelines/bootstrap_test.go:396]:
```suggestion
	err := fakeFs.MkdirAll(filepath.Join(params.OutputPath, ".git"), 0755)
```

File: pkg/pipelines/bootstrap.go [hunk 6]
```diff
@@ -471,6 +471,11 @@ func checkPipelinesFileExists(appFs afero.Fs, outputPath string, overWrite bool)
 	if secretsFolderExists && !overWrite {
 		return fmt.Errorf("the secrets folder located as a sibling of the output folder %s already exists. Rerun with --overwrite", outputPath)
 	}
+
+	gitDirectoryExists, _ := ioutils.IsExisting(ioutils.NewFilesystem(), filepath.Join(outputPath, ".git"))
+	if gitDirectoryExists && !overWrite {
+		return fmt.Errorf(".git in output path already exists. If you want to replace your existing files, please rerun with --overwrite")
+	}
 	return nil
 }
```
Comment (wtam2018) [inline pkg/pipelines/bootstrap.go:481]: We should clean this up.
```
// Checks whether the pipelines.yaml is present in the output path specified.
func checkPipelinesFileExists(appFs afero.Fs, outputPath string, overWrite bool) error {

	if overWrite {
		return nil
	}

	err := errorIfFileExists(appFs, outputPath, pipelinesFile, ".git")
	if err != nil {
		return err
	}

	secretsFolderExists, _ := ioutils.IsExisting(appFs, filepath.Join(outputPath, "..", "secrets"))
	if secretsFolderExists {
		return fmt.Errorf("the secrets folder located as a sibling of the output folder %s already exists. Rerun with --overwrite", outputPath)
	}

	return nil
}

func errorIfFileExists(appFs afero.Fs, outputPath string, files ...string) error {
	for _, file := range files {
		exists, _ := ioutils.IsExisting(appFs, filepath.Join(outputPath, file))
		if exists {
			return fmt.Errorf("%s in output path already exists. If you want to replace your existing files, please rerun with --overwrite", file)
		}
	}
	return nil
}
```

File: pkg/pipelines/utils.go [hunk 7]
```diff
@@ -74,6 +77,11 @@ func BootstrapRepository(o *BootstrapOptions, f clientFactory, e executor) error
 }
 
 func pushRepository(o *BootstrapOptions, remote string, e executor) error {
+	if exists, _ := ioutils.IsExisting(ioutils.NewFilesystem(), filepath.Join(o.OutputPath, ".git")); exists {
+		if err := os.RemoveAll(filepath.Join(o.OutputPath, ".git")); err != nil {
```
Comment (wtam2018) [inline pkg/pipelines/utils.go:81]: We should use afero.FS.

**Comment by wtam2018** [comment]
Please also test interactive mode.

File: pkg/pipelines/bootstrap.go [hunk 8]
```diff
@@ -461,16 +462,37 @@ func defaultPipelines(r scm.Repository) *config.Pipelines {
...
+
+	if pushToGit {
+		if err := errorIfFileExists(appFs, outputPath, ".git"); err != nil {
+			return err
+		}
+	}
+
+	if err := errorIfFileExists(appFs, outputPath, pipelinesFile); err != nil {
+		return err
 	}
```
Comment (wtam2018) [inline pkg/pipelines/bootstrap.go:479]:
```suggestion
	if pushToGit {
		checkList = append(checkList, ".git")
	}

	if err := errorIfFileExists(appFs, outputPath, checkList...); err != nil {
		return err
	}
```

File: pkg/cmd/bootstrap.go [hunk 9]
```diff
@@ -235,7 +234,12 @@ func initiateInteractiveMode(io *BootstrapParameters, client *utility.Client, cm
...
 	io.OutputPath, io.Overwrite = ui.VerifyOutputPath(io.OutputPath, io.Overwrite, outputPathOverridden, promptForAll)
-
+	if !io.Overwrite && io.PushToGit {
+		exists := ui.VerifyGitPath(io.OutputPath)
+		if exists {
+			return fmt.Errorf("the .git folder in output path %s already exists. Delete or rename the .git folder and try again", io.OutputPath)
+		}
+	}
 	if !io.Overwrite {
 		exists := ui.VerifySecretsPath(io.OutputPath)
```
Comment (wtam2018) [inline pkg/cmd/bootstrap.go:244]: move "if io.PushToGit {}" to here.

Comment (ishitasequeira) [reply pkg/cmd/bootstrap.go:238]: @wtam2018 Thanks for the review. Updated as you mentioned.

File: pkg/cmd/bootstrap.go [hunk 10]
```diff
@@ -235,12 +234,16 @@ func initiateInteractiveMode(io *BootstrapParameters, client *utility.Client, cm
 		io.OutputPath = filepath.Join(".", repoName)
 	}
 	io.OutputPath, io.Overwrite = ui.VerifyOutputPath(io.OutputPath, io.Overwrite, outputPathOverridden, promptForAll)
-
 	if !io.Overwrite {
 		exists := ui.VerifySecretsPath(io.OutputPath)
 		if exists {
 			return fmt.Errorf("the secrets folder located as a sibling of the output folder %s already exists. Delete or rename the secrets folder and try again", io.OutputPath)
 		}
```
Comment (wtam2018) [inline pkg/cmd/bootstrap.go:241]:
```suggestion
		if exists := ui.VerifySecretsPath(io.OutputPath); exists {
			return fmt.Errorf("the secrets folder located as a sibling of the output folder %s already exists. Delete or rename the secrets folder and try again", io.OutputPath)
		}
```

File: pkg/cmd/bootstrap.go [hunk 11]
```diff
@@ -235,12 +234,16 @@ func initiateInteractiveMode(io *BootstrapParameters, client *utility.Client, cm
...
+		if io.PushToGit {
+			if exists := ui.VerifyGitPath(io.OutputPath); exists {
+				return fmt.Errorf("the .git folder in output path %s already exists. Delete or rename the .git folder and try again", io.OutputPath)
+			}
+		}
```
Comment (wtam2018) [inline pkg/cmd/bootstrap.go:246]:
```suggestion
		if ui.PathExists(filepath.Join(io.OutputPath, "..", "secrets")) {
			return fmt.Errorf("the secrets folder located as a sibling of the output folder %s already exists. Delete or rename the secrets folder and try again", io.OutputPath)
		}
		if io.PushToGit && ui.PathExists(filepath.Join(io.OutputPath, ".git")) {
			return fmt.Errorf("the .git folder in output path %s already exists. Delete or rename the .git folder and try again", io.OutputPath)
		}
		}
```

File: pkg/cmd/ui/ui.go [hunk 12]
```diff
@@ -108,6 +108,12 @@ func VerifyOutputPath(originalPath string, overwrite, outputPathOverridden, prom
 	return outputPath, doOverwrite
 }
 
+func VerifyGitPath(outputPath string) bool {
+	exists, err := ioutils.IsExisting(ioutils.NewFilesystem(), filepath.Join(outputPath, ".git"))
+	handleError(err)
+	return exists
+}
```
Comment (wtam2018) [inline pkg/cmd/ui/ui.go:115]:
```suggestion
func PathExists(path string) bool {
	exists, err := ioutils.IsExisting(ioutils.NewFilesystem(), path)
	handleError(err)
	return exists
}
```

File: pkg/cmd/ui/ui.go [hunk 13]
```diff
@@ -108,6 +108,12 @@ func VerifyOutputPath(originalPath string, overwrite, outputPathOverridden, prom
...
+
```
Comment (wtam2018) [inline pkg/cmd/ui/ui.go:116]: Remove VerifySecretsPath()
change the ioutils func to use aferofs

Comment (ishitasequeira) [reply pkg/cmd/ui/ui.go:116]: Will remove verifySecretsPath().
ioutils.NewFileSystem() returns an instance of aferofs. Are you suggesting to replace it?

File: pkg/pipelines/bootstrap.go [hunk 14]
```diff
@@ -92,6 +92,7 @@ type BootstrapOptions struct {
 	PrivateRepoDriver        string               // Records the type of the GitOpsRepoURL driver if not a well-known host.
 	CommitStatusTracker      bool                 // If true, this is a "private repository", i.e. requires authentication to clone the repository.
 	Insecure                 bool                 // If true, use unencrypted, unsealed secrets. By default, sealed secrets are generated.
+	PushToGit                bool                 // records whether or not the repository should be pushed to git.
```
Comment (wtam2018) [inline pkg/pipelines/bootstrap.go:95]:
```suggestion
	PushToGit                bool                 // If true, gitops repository is pushed to remote git repository.
```

**Review by wtam2018 — COMMENTED** [review]
/lgtm
/approve
